#5 - Blog app - controllers specs
Amtresu/The-Minimalist-Place pull request #5
Opened 2022-11-28 22:50 UTC by Amtresu

- [ ] Add RSpec as a gem to your project.
- [ ] Create a Request spec file for all your controllers.
- [ ] Make sure that for each action you check:
- [ ] If response status was correct.
- [ ] If a correct template was rendered.
- [ ] If the response body includes correct placeholder text.

2022-11-28 23:20 UTC, Reem-lab reviewed
# Hi @Amtresu, 👋🏻 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, I think that you submit the wrong link to the wrong activity so kindly make sure to submit the right link since this is link for the views milestobe but you are making the controllers milestone 💯🚀✨

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-11-29 00:17 UTC, codepantha requested changes
# STATUS: CHANGES REQUIRED ♻️ 

## Hi @Amtresu 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media3.giphy.com/media/5w2544tNz4tAxbW9Nx/giphy.gif"/>

## Highlights 🎯 
✔️ Descriptive PR
✔️ Used GitFlow
✔️ Controller specs
✔️ Professional README
✔️ No linter errors

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- n/a

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-29 00:17 UTC, codepantha commented on spec/controllers/posts_spec.rb
> +    end
- [ ] The highlighted tests are failing. Kindly see the image attached below and try to make the failing tests green ✔️ 
![image](https://user-images.githubusercontent.com/46839548/204407017-d62cfce1-5c16-45a2-ae19-b97efd5be5bc.png)

2022-11-29 00:17 UTC, codepantha commented on spec/controllers/users_spec.rb
> +    end
- [ ] The following tests for the `show` action of the User are not passing. Please see the image attached below and try to make all the tests green ✔️ 
![image](https://user-images.githubusercontent.com/46839548/204407233-18bdfe84-ba3e-4d29-bdf1-98b15228aba8.png)

2022-11-29 00:23 UTC, Amtresu commented
Hi @codepantha These tests are passing on my end 
![image](https://user-images.githubusercontent.com/101094809/204408287-3fe09eeb-7114-4661-a165-9683695f9941.png)
So I will need more information about why they are failing for you to try and correct these.

2022-11-29 02:29 UTC, addod19 approved these changes
### Hi @Amtresu, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### Highlights
- [ ] Once all the test passed on your end and you have shown that with a screenshot :+1: we are good to go :rocket: 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-29 21:46 UTC, merged